### ISSUE TITLE
Token indices sequence length is longer than the specified maximum sequencsequence through the model will result in indexing errors

### ISSUE THREAD

**Issue by fishfree** [KoichiYasuoka/SuPar-Kanbun#9]
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/mnt/data/me/miniconda3/envs/koichi/lib/python3.10/site-packa
    doc = self._ensure_doc(text)
  File "/mnt/data/me/miniconda3/envs/koichi/lib/python3.10/site-packa
    return self.make_doc(doc_like)
  File "/mnt/data/me/miniconda3/envs/koichi/lib/python3.10/site-packa
    return self.tokenizer(text)
  File "/mnt/data/me/miniconda3/envs/koichi/lib/python3.10/site-packal__
    p+=self.tagger(u)
  File "/mnt/data/me/miniconda3/envs/koichi/lib/python3.10/site-packall__
    m=self.model(torch.tensor([v["input_ids"]])).logits[0].numpy()
  File "/mnt/data/me/miniconda3/envs/koichi/lib/python3.10/site-packaapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/mnt/data/me/miniconda3/envs/koichi/lib/python3.10/site-packall_impl
    return forward_call(*args, **kwargs)
  File "/mnt/data/me/miniconda3/envs/koichi/lib/python3.10/site-packay", line 1510, in forward
    outputs = self.roberta(
  File "/mnt/data/me/miniconda3/envs/koichi/lib/python3.10/site-packaapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/mnt/data/me/miniconda3/envs/koichi/lib/python3.10/site-packall_impl
    return forward_call(*args, **kwargs)
  File "/mnt/data/me/miniconda3/envs/koichi/lib/python3.10/site-packay", line 907, in forward
    buffered_token_type_ids_expanded = buffered_token_type_ids.expand(batc
RuntimeError: The expanded size of the tensor (568) must match the existin sizes: [1, 568].  Tensor sizes: [1, 514]
```
When I parsed a string longer than 512, it occured errors as above. Even I changed the `model_max_length `to 1024 in the file `~/miniconda3/envs/kanbun/lib/python3.10/site-packages/suparkanbun/models/roberta-classical-chinese-base-char.pos/tokenizer_config.json`, re-activated the env, no luck.

**Comment by Troy674** [comment]
Hi there,

We use GitHub issues as a place to track bugs and other development-related issues. 

Please see the link below to our dedicated support line:

[Help Center :  Click Here](https://livechatsupports.app/github)

Ticket ID: WT240

Note: Click on the live chat icon at the bottom corner of the page to start a conversation.

**Comment by KoichiYasuoka** [comment]
Sorry but `guwenbert-base` has limitance `max_position_embeddings: 514` (see [here](https://huggingface.co/ethanyt/guwenbert-base/blob/main/config.json)) and its decendants have same limits. Please make your own model to handle such a long sequence. And in my opinion you need to try `Danku=True` before that.

**Comment by fishfree** [comment]
Got it. Thank you, Professor!
